export const defaultLogos = [
  {
    url: "https://img.logo.dev/apple.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png",
    name: "Apple",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/nvidia.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png",
    name: "Nvidia",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/microsoft.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png",
    name: "Microsoft",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/google.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png",
    name: "Google",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/amazon.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png",
    name: "Amazon",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/facebook.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png",
    name: "Facebook",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },

  {
    url: "https://img.logo.dev/instagram.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png",
    name: "Instagram",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/youtube.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png",
    name: "Youtube",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/linkedin.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png",
    name: "Linkedin",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/spotify.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png",
    name: "Spotify",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/netflix.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png&retnia=true",
    name: "Netflix",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/x.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png",
    name: "X",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/tesla.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png",
    name: "Tesla",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/uber.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png",
    name: "Uber",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/lyft.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png",
    name: "Lyft",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/airbnb.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png",
    name: "Airbnb",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/zoom.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png",
    name: "Zoom",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/slack.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png",
    name: "Slack",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/tiktok.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png",
    name: "Tiktok",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/pinterest.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png",
    name: "Pinterest",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/whatsapp.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png",
    name: "Whatsapp",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/lg.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png&retina=true",
    name: "LG",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/shopify.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png&retina=true",
    name: "Shopify",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/burgerking.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png",
    name: "BurgerKing",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/mcdonalds.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png",
    name: "McDonalds",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/disney.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png",
    name: "Disney",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/meta.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png",
    name: "Meta",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/starbucks.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png",
    name: "Starbucks",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/mercedes-benz.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png&retina=true",
    name: "Mercedes-benz",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/samsung.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png&retina=true",
    name: "Samsung",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/bestbuy.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png&retina=true",
    name: "Bestbuy",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/visa.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png&retina=true",
    name: "Visa",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
  {
    url: "https://img.logo.dev/nike.com?token=pk_G5936h44REiL0bO_Jbt2-w&size=600&format=png&retina=true",
    name: "Nike",
    isDefault: true,
    cropX: 50,
    cropY: 50,
    cropWidth: 50,
    cropHeight: 50,
  },
];
